### ISSUE TITLE
Add ability to unlist an NFT to compliment listing one for sale

### ISSUE THREAD

**Issue by iangriggs** [Mintbase/mintbase-js#108]
At the moment, it appears that once an NFT is listed for sale via `wallet.list()` it isn't possible to cancel that operation.

Would it be possible to add a `wallet.unlist()` function? Assumption is needs complementary contract logic so not a quick fix?

**Comment by microchipgnu** [comment]
Hey! You can indeed use the `revokeAccount` method to remove the approval to the marketplace (`market.mintbase1.near`) or use `revokeAllAccounts` method to remove approvals for all accounts of a specific token.

- https://mintbase.github.io/mintbase-js/classes/wallet.Wallet.html#revokeAccount
- https://mintbase.github.io/mintbase-js/classes/wallet.Wallet.html#revokeAllAccounts

These probably need a better naming convention.

**Comment by microchipgnu** [comment]
Closing this issue.
