### ISSUE TITLE
[Mintbase-JS] Update mintbase.js login method to accept URL redirects

### ISSUE THREAD

**Issue by cif** [Mintbase/mintbase-js#116]
near-api-js allows the specification of [success and failure](https://github.com/near/near-api-js/blob/c567a8e752f86bfd4f89bd8ec775e94039ded4a1/lib/wallet-account.d.ts#L11) URLs. 

This will be useful not just for mintbase.js users, but for the marketplace login/auth flow refactoring

**Comment by microchipgnu** [comment]
https://github.com/Mintbase/mintbase-js/pull/119
