### ISSUE TITLE
Mintbase JS Refactoring Design

### ISSUE THREAD

**Issue by cif** [Mintbase/mintbase-js#132]
A plan for implementations of specific user use cases. 

As a mintbase platform developer I want to ______ so that I can ______ 

https://docs.google.com/document/d/1SA9Pt5_CKe8Im5IkharpvLyTBBjNF_1grwkTB-1dDKI/edit#heading=h.pz2xgamr4nqp

**Comment by cif** [comment]
This task is going to be a meeting.

**Comment by microchipgnu** [comment]
Shall we have this meeting next Monday? Before sprint planning?

**Comment by cif** [comment]
Scheduled
