### ISSUE TITLE
Mint method doesn't execute.

### ISSUE THREAD

**Issue by jothamardel** [Mintbase/mintbase-js#185]
I bootstrapped my project from Mintbase Boilerplate and Starter for Next JS 12+, Tailwind CSS 3, and TypeScript.

The application successfully connects to a near wallet when the connect method is invoked, but when I call the
`wallet.mint()` nothing happens.

I implemented it in a previous version of the application and it worked but it doesn't seem to work on this recent project I'm working on.

What could be the issue?

**Comment by microchipgnu** [comment]
Hey @jothamardel I would take a look into the new MintbaseJS (https://docs.mintbase.io/dev/mintbase-sdk-ref)

Specifically, take a look into the `mint` method. https://docs.mintbase.io/dev/mintbase-sdk-ref/sdk/mint
