### ISSUE TITLE
Incorrect near account listed as NFT owner

### ISSUE THREAD

**Issue by charleslavon** [Mintbase/mintbase-js#412]
The NFTs of the contract at [v0.8bityonce.near](https://www.mintbase.xyz/contract/v0.8bityonce.near/nfts/all/0) all listed as being owned by 8bityonce.near. However 3 of these NFTs have successfully been transferred to other accounts.

[keypom-146-0-8bityonce.near-1672417819217](https://nearblocks.io/txns/BqiPRu96JMMi8c3zwZoS91z5j2Mm8EzxtXsHWgcMFtnz#execution)
[keypom-146-1-8bityonce.near-1672417833489](https://nearblocks.io/txns/BUV8iAJb8NuqHvBQN7qw2AriLWhNjuPWmu85VRRcX7Mh#execution)
[keypom-146-2-8bityonce.near-1672417847792](https://nearblocks.io/txns/AGZE6dUw2s8eZfqHco8jmH6GsH9YuyG8gRcLfDVEQBXK#execution)

Is there an issue resolving the owner of NFTs when the NFT contract is deployed on a sub-account?

**Comment by tifrel** [comment]
Looks like event logs are missing the `EVENT_JSON:` prefix on the smart contract in question, resulting in the indexer being unable to pick up those transfers
