### ISSUE TITLE
Bitte Wallet contractId options

### ISSUE THREAD

**Issue by hanakannzashi** [Mintbase/mintbase-js#537]
Bitte Wallet didn't read the `contractId` which is configured in `setupModal` nor create a function call key when login. This behavior is different from other wallets such as Meteor, MyNearWallet, etc.

**Comment by SurgeCode** [comment]
You need to pass the contractId into the setupBitteWallet to enable the limited access key otherwise it will skip it automatically

https://github.com/near/wallet-selector/blob/main/packages/bitte-wallet/README.md
